### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mesuutt** [mesuutt/telegder#1]
- [ ] Balance report: `-collapse` and `--flat`
- [ ] Export / clear downloaded transactions
- [ ] Writing alias or related account to ledger file can be set as settings
- [ ] Budgets
- [ ] Execution of custom ledger commands and saving it as alias: `xa <args>`
- [ ] Raw transaction insertion mode
- [ ] Daily reminder

**Comment by mesuutt** [comment]
![acc-300](https://user-images.githubusercontent.com/823338/75116846-5e3a4800-567d-11ea-84b7-b22c1a22ed69.jpeg)
